import os 

FROM_WEBFLOW_SITE_ID=os.environ['FROM_WEBFLOW_SITE_ID']
FROM_WEBFLOW_ACCESS_TOKEN=os.environ['FROM_WEBFLOW_ACCESS_TOKEN']
TO_WEBFLOW_SITE_ID=os.environ['TO_WEBFLOW_SITE_ID']
TO_WEBFLOW_ACCESS_TOKEN=os.environ['TO_WEBFLOW_ACCESS_TOKEN']